### ISSUE TITLE
timeToDie

### ISSUE THREAD

**Issue by rayfish** [kirk24788/KPS#21]
This is a feature request for timetodie. Looking at the jps version is seems to have a lot of complicated algorithms so I understand that it is hard to port over. 

However it would be very, very useful for Legion leveling. For example I'm thinking of leveling as Feral and without timeToDie there will be a very high DPS loss because the rotation will spend 5 combo points on a Rip DoT that only ticks once because the mob is >20% but about to die in 3 seconds. Rogues and probably other classes may have similar problems.

Is there perhaps a workaround so we can use the old wowace timeToDie addon as a dependency that can be used inside KPS rotations? It wasn't updated in a long time but still works ok. https://www.wowace.com/addons/timetodie/

**Comment by kirk24788** [comment]
> Looking at the jps version is seems to have a lot of complicated algorithms so I understand that it is hard to port over.
Well...thanks I guess. I wrote the Code in JPS...so no, it's not that hard to, but it takes some time.
The main problem ist not converting (that would be easy) but making it load on demand, I don't want all rotations to suffer performance issues, because only a few need this feature

If you look at the Readme, you should see:
> modules/unit/unit_powers.lua:47 - TimeToDie
It's planned...but I never managed to implement it. I'm rather short on time, so don't expect it soon...I'm currently busy with Keymoon 2.0, but as there seems to be some interest - I'll get the time to finish it within the next 1-2 weeks...
e. 

Regarding the workaround...nah, I'll implement it properly, I guess this will be better.
